# Jekyll config

# Setup

title: LEB PAC
tagline: L'École Bilingue Parent Advisory Council
description: L'École Bilingue<br>Parent Advisory Council
url: https://lebpac.ca

# GitHub config settings
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
