# Jekyll config

# Setup

title: LEB PAC
tagline: L'École Bilingue Parent Advisory Council
description: Get involved with your school!
url: https://lebpac.ca
permalink: /:categories/:year/:month/:day/:title

# Sidebar

sidebar_pages:
  - about.md
  - calendar.md
  - volunteer.md
  - fundraising.md
  - programs.md
  - lunch.md
  - meetings.md
  - newsletter.md

# GitHub config settings
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugins

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Excludes

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
